
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=django_password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  web:
    build: .
    env_file:
      - ./.env
    depends_on:
      - db
    ports:
      - "8000:8000"


volumes:
  postgres_data:
    name: postgres_data
