# Generated by Django 5.1.7 on 2025-07-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_favorite_game_alter_favorite_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='img',
            field=models.ImageField(default='default/default.png', upload_to='game_img/'),
        ),
    ]
